### ISSUE TITLE
Feature Request: Import hosts from file

### ISSUE THREAD

**Issue by Junohea** [nccgroup/redsnarf#1]
Would like to request a feature to allow the use of a text file as the input for target IPs. Portions of ranges are often excluded by clients so allowing a list as input would be super helpful 😄

**Comment by llandeilocymro** [comment]
Yes - that seems sensible. I believe our internal version does this
already.

**Comment by dickdavy** [comment]
Hi, thanks for your feature request, functionality to Import hosts from file has now been added. 

To test a single host use -H ip=10.0.0.1
To test a range use -H range=10.0.0.1/24
To import hosts use -H file=targetfile.txt

Any problems let us know.
