### ISSUE TITLE
run redsnarf with error

### ISSUE THREAD

**Issue by ztencmcp** [nccgroup/redsnarf#4]
Hello, 

When i run redsnarf in Kali OS, i get this error, could you please help me out ? Thanks!

python redsnarf.py 
Traceback (most recent call last):
  File "redsnarf.py", line 239, in <module>
    from nmb.NetBIOS import NetBIOS
ImportError: No module named nmb.NetBIOS

**Comment by dickdavy** [comment]
Hi ztencmcp,

The following should sort things out.
pip install pysmb

Cheers, Rich.

**Comment by ztencmcp** [comment]
Thank you ! i installed the module manually, but i found a bug when the password include the special character like "!" then redsnarf will recognize it as script. is there any solution?

**Comment by dickdavy** [comment]
escape the ! by putting a \ before it so example P!assword would be P\!assword

**Comment by jiraiyalegendarysannin** [comment]
Hi @dickdavy, The exclamation mark is part of history expansion in bash, so there is nothing wrong with the redsnarf. By the way, you can also put single quote around your password like 'P!assword'.
